Open encrypted file and write back the category to the transaction
psybers/actual-chatgpt pull request #1
Opened 2024-05-28 15:11 UTC by MotafokaBR

- Included an optional environment variable to get the password for encrypted files

- Changed the download step to open encrypted files
- Included an extra step to write back the transaction with the ChatGPT category

2024-05-28 15:14 UTC, MotafokaBR commented
I have been using weekly for the past few weeks and it works wonders.

2024-05-28 19:57 UTC, psybers requested changes

2024-05-28 19:57 UTC, psybers commented on suggest-cats.js
> +      }
Can you remove this from this PR?  I planned to allow updates, but I wanted to make those optional and have the possibility of being interactive (to confirm each one before updating).

2024-05-29 20:27 UTC, MotafokaBR reviewed
Not sure if I'm doing this right

2024-05-29 20:28 UTC, merged

2024-05-29 20:28 UTC, psybers commented
Looks good, thank you!